### PR TITLE
grunt test fails on windows

### PR DESCRIPTION
**Pull request by jpommerening**
```
> grunt test
Running "clean:test" (clean) task

Running "clean:fixtures" (clean) task

Running "fixtures" task
>> Installing bower packages in tasks/spec/fixtures
Fatal error: spawn ENOENT
```

### CODE REVIEW

**Comment by jpommerening** [comment]
1) laxarPaths( config, [options] ) when called with a require configuration resolves the laxar path constants with the given require configuration:
       expected "C:\Users\jpommerening\grunt-laxar\lib\spec/root" to equal "C:\Users\jpommerening\grunt-laxar\lib\spec\root"

This happens because the test uses `__dirname` as a base URL for (essentially) testing `require.toUrl()`, thus mixing forward and backward slashes. Since RequireJS operates on URLs (not filesystem paths) the test should use a URL instead of `__dirname` (it does not need to be reachable).

**Comment by jpommerening** [comment]
1) mktree( base, filelist, embedContents, callback ) when called with a list of files and a callback builds a tree-like structure from the given paths:
       Cannot read property 'spec' of undefined

    2) mktree( base, filelist, embedContents, callback ) when called with a list of files and a callback records the file type (directory or file) for each given file:
       expected {"tasks": 0, "lib/spec/data/require_config_a.js": 1, "lib/spec/data/require_config_b.js": 1} to equal {"tasks": 0, "lib": {"spec": {"data": {"require_config_a.js": 1, "require_config_b.js": 1}}}}

The `mktree` function tries to split paths by the OS's usual path name separator, to create the tree object. Unfortunately it operates on a list obtained from `grunt.file.expand` which always has UNIX-style paths with forward slashes.

**Comment by jpommerening** [comment]
4) mktree( base, filelist, embedContents, callback ) when asked to embed contents embeds the requested contents:
       timeout of 2000ms exceeded

Embedding stuff seems to cause timeouts, probably caused by unresolved promises. Maybe `fs.readFileSync` is behaving oddly? I'm stuck and can't figure out what's causing this…

**Comment by jpommerening** [comment]
1) WidgetCollector finds all widgets in a page declaration:
       expected {} to be falsey

Aaaand another one. This seems to be some path separator confusion again.

**Comment by jpommerening** [comment]
What remains are timeouts when running the tasks tests. I'm not yet sure what's causing these, so that still needs to be investigated :weary:

**Comment by x1B** [comment]
@jpommerening could you get around this problem by checking the error argument before calling `expect`?

**Comment by jpommerening** [comment]
Nope, this time it's the `before()` that is running the task that never finishes…

**Comment by jpommerening** [comment]
Phew, alrighty, thanks to @x1B for helping out! The `.gitattributes` took a few tries to get right.
Also: The page loader (used by `css_merger` and `laxar_application_dependencies`) works better when the supplied path is `path.resolve()`d.

The timeouts were caused by the `laxar_application_dependencies` task. There's a promise chain in there that uses `.catch( grunt.fail.fatal )` and that killed the Grunt instance that's running the tasks that are tested. Instead of passing in `grunt.fail.fatal` the tasks `done` callback should be used to signal an error.

**Comment by jpommerening** [comment]
Rebased on master for easy merging and #37 fixes, squashed some commits.

**Pull request merged**
